[workspace]
members = [
    "compute_tools",
    "control_plane",
    "pageserver",
    "proxy",
    "safekeeper",
    "workspace_hack",
    "neon_local",
    "libs/*",
]

[profile.release]
strip = "debuginfo"

[profile.perf]
inherits = "release"
debug = true

[profile.release-coverage]
inherits = "release"
overflow-checks = true
debug-assertions = true

# This is only needed for proxy's tests.
# TODO: we should probably fork `tokio-postgres-rustls` instead.
[patch.crates-io]
tokio-postgres = { git = "https://github.com/zenithdb/rust-postgres.git", rev="d052ee8b86fff9897c77b0fe89ea9daba0e1fa38" }
