[package]
name = "pageserver_client"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
pageserver_api.workspace = true
thiserror.workspace = true
async-trait.workspace = true
reqwest.workspace = true
utils.workspace = true
serde.workspace = true
workspace_hack = { version = "0.1", path = "../../workspace_hack" }
