[package]
name = "pageserver_client"
version = "0.1.0"
edition.workspace = true


[dependencies]
pageserver_api.workspace = true
thiserror.workspace = true
async-trait.workspace = true
reqwest.workspace = true
utils.workspace = true
serde.workspace = true
